site_name: LabPartner - A Tool for Undergraduate Physics Students
nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting_started.md
  - Tutorials: tutorials.md
  - FAQ: faq.md
  - Contact: contact.md

theme: readthedocs
